version: '3'

services:
  inst-nginx:
    networks:
      - inst-internal
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
      - ./docker/server-logs:/var/log/nginx

  inst-fpm:
    networks:
      - inst-internal
    environment:
      XDEBUG_CONFIG: client_host=docker.for.mac.localhost remote_enable=1 client_port=9000
      XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=localhost
      DATABASE_URL: 'mysql://inst:inst@inst-db/inst'
    volumes:
      - ./:/var/www/html/
      - ./docker/server-logs:/var/log/nginx

  inst-db:
    ports:
      - 3304:3306
    volumes:
      - inst-db-data:/var/lib/mysql
    networks:
      - inst-internal
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'inst'
      MYSQL_USER: 'inst'
      MYSQL_PASSWORD: 'inst'

networks:
  inst-internal:
    driver: bridge

volumes:
  inst-db-data: ~
