version: "3"

services:
  inst-nginx:
    container_name: inst-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    environment:
      PHP_HOST: inst-fpm

  inst-fpm:
    container_name: inst-fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile

  inst-db:
    container_name: inst-db
    image: percona:5.7
